fixes #364 link demos
WestpacGEL/GEL-next pull request #374
Opened 2023-11-24 04:25 UTC by kenjishiromajp

2023-11-24 04:42 UTC, jaortiz requested changes

2023-11-24 04:42 UTC, jaortiz commented on apps/site/src/content/design-system/components/link/design/Standalone/content.mdoc
>  <div className="flex flex-col pl-1 space-y-1">
Delete this duplicate file and folder

2023-11-27 08:21 UTC, samithaf approved these changes

2023-11-27 10:01 UTC, jaortiz approved these changes

2023-11-27 10:02 UTC, merged