Fix/style fixes
WestpacGEL/GEL-next pull request #916
Opened 2024-10-28 01:24 UTC by HZ991

Work in progress PR.
Includes following changes:
- progress indicator component upgrade
- protoform and ui style/visual bug fixes

2024-10-31 11:24 UTC, jaortiz requested changes
Also add more tests now progress indicator has more functionality

2024-10-31 11:24 UTC, jaortiz commented on packages/ui/src/components/progress-indicator/progress-indicator.component.tsx
> +  embedIcon: EmbedIcon,
Rename this to just be `icon: Icon` to be consistent with how we take icons in other components

2024-10-31 11:24 UTC, jaortiz commented on packages/ui/src/components/progress-indicator/progress-indicator.component.tsx
> +  inverted = false,
As discussed revert back to color prop to be aligned with icon props

2024-11-01 04:55 UTC, HZ991 commented on packages/ui/src/components/progress-indicator/progress-indicator.component.tsx
> +  embedIcon: EmbedIcon,
is icon: EmbedIcon ok, it is just conflicting with the other 'Icon' import

2024-11-13 23:40 UTC, jaortiz requested changes

2024-11-13 23:40 UTC, jaortiz commented on packages/ui/src/components/progress-indicator/progress-indicator.component.tsx
> +  inverted = false,
Remove inverted since we are using color prop

2024-11-13 23:40 UTC, jaortiz commented on packages/ui/src/components/progress-indicator/progress-indicator.component.tsx
> +          color={inverted ? 'white' : 'hero'}
Update to pass `color` prop through

2024-11-13 23:40 UTC, jaortiz commented on packages/ui/src/components/progress-indicator/progress-indicator.component.tsx
> +        {EmbedIcon && size === 'large' && <EmbedIcon size="large" className={styles.icon()} />}
Need to pass `color` prop through to the embedded icon here too

2024-11-13 23:40 UTC, jaortiz commented on packages/ui/src/components/progress-indicator/progress-indicator.styles.ts
> +    compoundSlots: [
Need to update to use the color prop to update the text color

2024-11-13 23:40 UTC, jaortiz commented on packages/ui/src/components/progress-indicator/progress-indicator.types.ts
> +  inverted?: boolean;
Remove inverted type

2024-11-18 03:32 UTC, jaortiz commented on packages/ui/src/components/progress-indicator/progress-indicator.types.ts
> +export type ProgressIndicatorProps = IconProps & {
Minor: Update to `Omit<IconProps, 'copyrightYear' | 'look'>`

2024-11-18 10:33 UTC, jaortiz approved these changes

2024-11-18 10:33 UTC, merged